### ISSUE TITLE
BoneAppetit - Sound Effects

### ISSUE THREAD

**Issue by NicTerrio** [RockerKitten/BoneAppetit#1]
Hiya - LOVE this Mod but the sound effects are not the same level as the game sounds...any way you can equalize them?  Any time I need to create something, it's super loud.  Thanks!

**Comment by RockerKitten** [comment]
yah, the guy who's helping me with my code mentioned that as well. he also said he knows how to fix it so, I'm hoping to have a fix with the next update.

**Comment by NicTerrio** [comment]
YOU ROCK! =)

**Comment by RockerKitten** [comment]
was fixed in 2.1
