### ISSUE TITLE
[Bug] Prep Table lightning Issue

### ISSUE THREAD

**Issue by spannerman79** [RockerKitten/BoneAppetit#10]
I thought it would be easier to show

https://youtu.be/T7aFfeaDC3Q

The little fire under the pot cycles to an off state each time.  As if the animation starts or continues at the incorrect place.

Mod version: https://valheim.thunderstore.io/package/RockerKitten/BoneAppetit/3.0.4/

**Comment by peachmimosa15** [comment]
i agree one time i built a barrier around it bc it became strobe lights in my house and i couldnt focus. lol

**Comment by RockerKitten** [comment]
fixed by removing the light
