### ISSUE TITLE
Mod BoneAppetit v3.0.2 is not installed on the server.

### ISSUE THREAD

**Issue by shayeryan** [RockerKitten/BoneAppetit#12]
I'm getting this error when trying to join my server: **Mod BoneAppetit v3.0.2 is not installed on the server.**

Others are as well:
https://www.nexusmods.com/valheim/mods/1250?tab=bugs

I have the latest version installed on server/client. I'm using the Thunderstore Mod Manager. 

I've tried reinstalling on both.

**Comment by sbtoonz** [comment]
Closing as - OLD STALE
