### ISSUE TITLE
Added the Oven next to a lit grill, no new reciepe.

### ISSUE THREAD

**Issue by Myndmelt** [RockerKitten/BoneAppetit#18]
Hi Curious if this is working correctly.
I'm on version 3.2.0

We added a grill with a fire and that works great but we added a Oven right next to the grill. 
The Grill updates number to 2. Should I be seeing new recipes with the oven addon? 
If not, what is the advantage of the Oven?

Thank you!

**Comment by RockerKitten** [comment]
It would depend on if you have all of the ingredients unlocked as well.

**Comment by Myndmelt** [comment]
Oh right thank you RockerKitten
