### ISSUE TITLE
Mistlands Update

### ISSUE THREAD

**Issue by SaltSouls** [RockerKitten/BoneAppetit#19]
It would be nice to get an official update adding support for Mistlands. It would seem Mistlands has broken a couple of things like the chefs hat glowing in the dark, the cooking skill name/icon being broken, and the cooking table being generally kinda buggy as well as some items(pork rinds plate for one) seemingly missing textures. The mod mostly works, but it seems like a few things need to be updated for full compatibility with the newest version of the game.

**Comment by SaltSouls** [comment]
Also getting this error:
```
[Error  :Boneappetit.BoneAppetit] Error while running OnVanillaLoad: Object reference not set to an instance of an object
```

**Comment by RockerKitten** [comment]
updated
