### ISSUE TITLE
Almost all food needs rebalance

### ISSUE THREAD

**Issue by originalWiFiN** [RockerKitten/BoneAppetit#20]
Recently I made my own modpack that includes this mod and noticed that players are eating mostly bacon and smoked fish, while we are almost swamps-worthy. Dug into the numbers and holy sh*t, your food gives WAY more stats than it should at the current biome. Especially simple single-component stuff.

I'm gonna rebalance it through wackyDB's json overrides, but if you need help with that, I can contribute to the base mod.

Here's what it looks like right now. Red is health, yellow is stamina, green is hp regen. As you can see most of the items from BoneAppetit shoot into the next biome, which is not okay. 
![image](https://user-images.githubusercontent.com/11654810/214569849-5ff219ff-b619-489b-baaf-a1cf5e22e01a.png)
![image](https://user-images.githubusercontent.com/11654810/214569734-e58868ab-3e52-4f37-aa1f-d33952eb16d4.png)

**Comment by Brennan-OCP** [comment]
Any chance you could share the changes you made in wacky @originalWiFiN? I am looking to do something similar and trying to figure out how best to balance the food items.

**Comment by BlackfishStudios** [comment]
Hey @originalWiFiN, would you mind sharing any info on the changes you made in Wacky? I'm looking for a baseline/comparison to do something similar on rebalancing the food.

**Comment by sbtoonz** [comment]
balance is set

up to end user to modify if they so desire through wackydb or other mods
