### ISSUE TITLE
Smokeless Piece Icon Issues

### ISSUE THREAD

**Issue by ValhallaCommunity** [RockerKitten/BoneAppetit#29]
![image](https://user-images.githubusercontent.com/124803112/231053366-47847fe2-a494-4dfb-8e97-364fc6682a81.png)
![image](https://user-images.githubusercontent.com/124803112/231053429-690b5e14-b047-446e-bbfa-dd5f67f3bd5e.png)

Hey RockerKitten,

We updated to the most recent version in our server and the icons are not displaying in build hammer and VNEI.

Let me know if you need additional details!

Thank you!

**Comment by sbtoonz** [comment]
Will resolve

**Comment by sbtoonz** [comment]
fixed in 3.2.7
