### ISSUE TITLE
Boiled Egg - Icon Issue

### ISSUE THREAD

**Issue by ValhallaCommunity** [RockerKitten/BoneAppetit#34]
Hey RK! sorry for the bombardment of issues!

![image](https://user-images.githubusercontent.com/124803112/232375332-f4ca5207-8186-4893-9637-6847ed2304ec.png)

I think there used to be a different icon for the boiled egg. Can you confirm?

Thank you!

**Comment by ValhallaCommunity** [comment]
![image](https://user-images.githubusercontent.com/124803112/232375400-110d3676-3822-49a3-a3cb-e6949314d876.png)

Shows as a different egg

**Comment by sbtoonz** [comment]
3.3.0 fixes
