### ISSUE TITLE
3.2.9 smokeless fire missing logs [cosmetic bug]

### ISSUE THREAD

**Issue by TheCloudCrafter** [RockerKitten/BoneAppetit#37]
![image](https://user-images.githubusercontent.com/53633953/232644245-01e4540a-eac6-4f07-adba-5b3087f9c171.png)

**Comment by sbtoonz** [comment]
Thanks a couple folks on discord reported this too, Will push an update this week to fix the various looming bugs

**Comment by sbtoonz** [comment]
3.3.0 fixes
