### ISSUE TITLE
Uncraftable(buildable?) food stations

### ISSUE THREAD

**Issue by Rensik** [RockerKitten/BoneAppetit#9]
I seem to be unable to build any food stations from this mod. I am currently weeding out mods to find the conflict, but was wondering if there were any known incompatibilities with other mods?

**Comment by Rensik** [comment]
Found the conflict: RRRCore or a mod in that series. Didn't take the time to narrow it down. I just removed the entire set.

**Comment by sbtoonz** [comment]
Closing as - OLD STALE
